### ISSUE TITLE
Not able to import an APP

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#470] opened 2020-09-22 10:39 UTC
**Description**:
When trying to import an APP it results in a "node existing error" and it's not possible to import the APP.

**Step by Step**

1. Once in the dashboard and in the APP's section, click on import.
2. Try to upload the Key file of an existing APP.
3. Provide the passphrase.
4. Click on "continue".
5. Notice the "Node existing error".
6. 

**Evidence**:
![Screen Shot 2020-09-22 at 7 50 26 AM](https://user-images.githubusercontent.com/17748171/93873567-4c1e9780-fca8-11ea-8bd8-47dd9d1a9dc2.png)

**Comment by pabelnl** [comment] 2020-09-22 18:35
Duplicate of #465, issue fixed in PR #478

**Closed as completed by pabelnl** 2020-09-22 18:35 UTC
Labels: Bug
